### ISSUE TITLE
Ankh Credit release 1.0.2 is mislabelled as Ankh Electrum 

### ISSUE THREAD

**Issue by gwestwood** [Ankh-Trust/credit-core#1]
The 1.0.2 release on the credit-core GitHub at https://github.com/Ankh-Trust/credit-core/releases/tag/v1.0.2.0 has been mislabelled "Ankh Electrum (0AE) v1.0.2.0 Release".  Please can this be corrected to avoid confusion?

**Comment by razerrazer** [comment]
edited, thanks!
